### ISSUE TITLE
Time selection gets deleted if in 'section' you then press 'prev' or 'next'

### ISSUE THREAD

**Issue by bjg321** [navelpluisje/reasonus-install#29]
**Describe the bug**
I make a time selection in the timeline. But then, if I'm in 'section' navigator, the time selection gets deleted if I press'prev' or 'next'

**Operating System**
- [] Windows 10

**Versions**
Versions can be found on the About page of the installer
- Reasonus Installer: ...
- Reasonus Resources: ... v1.01
- CSI (ReaSonus): ... CSI 2, as far as I can tell. I updated to 2 this morning.

**Expected behavior**
A clear and concise description of what you expected to happen. - I didn't expect my time selection to disappear. In fact, if I use my keyboard shortcuts to move from one marker to the next, they also land on the start and end of the time selection. 

**Screenshots**

**Additional context**

**Comment by maldomusica** [comment]
Hi. Where is the second version of csi?

**Comment by navelpluisje** [comment]
This version of ReaSonus FaderPort will only work with the CSI version it got supplied with. This because of changes made to make it work properly.

There still is a plann for updating. I started it and got more things I had to work around the I expected. Also due to some other thing going on ReaSonus has a bit lower priority then I want it to have.

Sorry for that
